os: osx
language: objective-c
matrix:
  include:
    - {osx_image: xcode8.3,   env: 'PLAT=macOS   SWFT=3.1 DST="arch=x86_64"'}
    - {osx_image: xcode8.3,   env: 'PLAT=iOS     SWFT=3.1 DST="OS=10.3.1,name=iPhone SE"'}
    - {osx_image: xcode8.3,   env: 'PLAT=tvOS    SWFT=3.1 DST="OS=10.2,name=Apple TV 1080p"'}

    - {osx_image: xcode9.2,   env: 'PLAT=macOS   SWFT=3.2 DST="arch=x86_64"'}
    - {osx_image: xcode9.2,   env: 'PLAT=iOS     SWFT=3.2 DST="OS=11.2,name=iPhone SE"'}
    - {osx_image: xcode9.2,   env: 'PLAT=tvOS    SWFT=3.2 DST="OS=11.2,name=Apple TV"'}

    - {osx_image: xcode9.3,   env: 'PLAT=macOS   SWFT=3.3 DST="arch=x86_64"'}
    - {osx_image: xcode9.3,   env: 'PLAT=iOS     SWFT=3.3 DST="OS=11.3,name=iPhone SE"'}
    - {osx_image: xcode9.3,   env: 'PLAT=tvOS    SWFT=3.3 DST="OS=11.3,name=Apple TV"'}

    - {osx_image: xcode9.2,   env: 'PLAT=macOS   SWFT=4.0 DST="arch=x86_64"'}
    - {osx_image: xcode9.2,   env: 'PLAT=iOS     SWFT=4.0 DST="OS=11.2,name=iPhone SE"'}
    - {osx_image: xcode9.2,   env: 'PLAT=tvOS    SWFT=4.0 DST="OS=11.2,name=Apple TV"'}

    # This variant fails reliably with Xcode 9.3, so sticking to Xcode 9.2 for now
    - {osx_image: xcode9.2,   env: 'PLAT=iOS     SWFT=4.0 DST="OS=8.4,name=iPhone 4s"'}

    - {osx_image: xcode9.3,   env: 'PLAT=macOS   SWFT=4.1 DST="arch=x86_64"'}
    - {osx_image: xcode9.3,   env: 'PLAT=iOS     SWFT=4.1 DST="OS=9.3,name=iPhone SE"'}
    - {osx_image: xcode9.3,   env: 'PLAT=iOS     SWFT=4.1 DST="OS=10.3.1,name=iPhone SE"'}
    - {osx_image: xcode9.3,   env: 'PLAT=iOS     SWFT=4.1 DST="OS=11.2,name=iPhone SE"'}
    - {osx_image: xcode9.3,   env: 'PLAT=tvOS    SWFT=4.1 DST="OS=9.2,name=Apple TV 1080p"'}
    - {osx_image: xcode9.3,   env: 'PLAT=tvOS    SWFT=4.1 DST="OS=10.2,name=Apple TV 1080p"'}
    - {osx_image: xcode9.3,   env: 'PLAT=tvOS    SWFT=4.1 DST="OS=11.2,name=Apple TV"'}
cache:
  directories:
  - Carthage
before_install:
  - carthage bootstrap --cache-builds --no-use-binaries --platform $PLAT --verbose
install:
  - xcodebuild -scheme PMKStoreKit -quiet -destination "$DST" build-for-testing SWIFT_VERSION=$SWFT
script:
  - xcodebuild -scheme PMKStoreKit -quiet -destination "$DST" test
