name: CI
on:
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.xcode == '11' && 'macos-10.15' || 'macos-11' }}
    strategy:
      matrix:
        platform:
          - macOS
          - tvOS
          - iOS
          - watchOS
        xcode:
          - 11
          - 12
          - 13
    steps:
    - uses: actions/checkout@v2
    - run: rm -rf PMKStoreKit.xcodeproj
    - uses: mxcl/xcodebuild@v1
      with:
        xcode: ${{ matrix.xcode }}
        platform: ${{ matrix.platform }}
        action: build
